table FactSales
	lineageTag: f10de4e7-f503-4618-abe4-edb0847ccda1

	measure 'Gross Sales' = SUM ( FactSales[GrossSalesAmount] )
		formatString: £#,0
		displayFolder: Sales\Core
		lineageTag: c451163c-2710-4d5c-8beb-60cda4983218

	measure 'Return Amount' = SUM ( FactSales[ReturnAmount] )
		formatString: £#,0
		displayFolder: Sales\Core
		lineageTag: 217d51bb-af31-497e-86b6-1edeb8756fe7

	measure 'Net Sales' = SUM ( FactSales[NetSalesAmount] )
		formatString: £#,0
		displayFolder: Sales\Core
		lineageTag: 52ef1f01-6a5c-4d1a-96ab-ab0f76ad6de2

	measure 'Units Sold' = SUM ( FactSales[UnitsSold] )
		formatString: #,0
		displayFolder: Sales\Core
		lineageTag: 39027bc3-ad88-42a6-8eb2-6e38571fda2b

	measure 'Returned Units' = SUM ( FactSales[ReturnedUnits] )
		formatString: #,0
		displayFolder: Sales\Core
		lineageTag: 062425be-20b5-42c7-9f91-de800c673d81

	measure Orders = CALCULATE ( DISTINCTCOUNT ( FactSales[InvoiceNo] ), FactSales[IsCancellation] = FALSE () )
		formatString: #,0
		displayFolder: Sales\Core
		lineageTag: 15da1106-4050-4d06-8e79-6e8e5826ef07

	measure Customers = CALCULATE ( DISTINCTCOUNT ( FactSales[CustomerID] ), FactSales[CustomerID] <> "Unknown" )
		formatString: #,0
		displayFolder: Sales\Core
		lineageTag: c9216c4f-1be0-4a16-9c3d-d68af415994c

	measure 'Average Order Value' = DIVIDE ( [Net Sales], [Orders] )
		formatString: £#,0.00
		displayFolder: Sales\Efficiency
		lineageTag: 99e6af0c-211f-4618-80e1-564be4d9520a

	measure 'Average Selling Price' = DIVIDE ( [Gross Sales], [Units Sold] )
		formatString: £#,0.00
		displayFolder: Sales\Efficiency
		lineageTag: c4168361-8193-49a4-a13b-58b964448647

	measure 'Return Rate' = DIVIDE ( [Return Amount], [Gross Sales] )
		formatString: 0.0%
		displayFolder: Sales\Quality
		lineageTag: e74fa4ad-bc64-4bcc-a04a-3c500e5e6eba

	measure 'Net Sales Previous Month' = VAR MaxSalesDate = MAX ( FactSales[SalesDate] ) VAR CurrentDate = IF ( MaxSalesDate < EOMONTH ( MaxSalesDate, 0 ), EOMONTH ( MaxSalesDate, -1 ), MaxSalesDate ) VAR PreviousDate = EOMONTH ( CurrentDate, -1 ) RETURN CALCULATE ( [Net Sales], FILTER ( ALL ( DimDate ), DimDate[Year] = YEAR ( PreviousDate ) && DimDate[MonthNumber] = MONTH ( PreviousDate ) ) )
		formatString: £#,0
		displayFolder: Sales\Movement
		lineageTag: 32cceb3a-dd6c-4940-8f34-78a2c3d6d607

	measure 'Net Sales MoM' = VAR MaxSalesDate = MAX ( FactSales[SalesDate] ) VAR CurrentDate = IF ( MaxSalesDate < EOMONTH ( MaxSalesDate, 0 ), EOMONTH ( MaxSalesDate, -1 ), MaxSalesDate ) VAR CurrentValue = CALCULATE ( [Net Sales], FILTER ( ALL ( DimDate ), DimDate[Year] = YEAR ( CurrentDate ) && DimDate[MonthNumber] = MONTH ( CurrentDate ) ) ) RETURN DIVIDE ( CurrentValue - [Net Sales Previous Month], [Net Sales Previous Month] )
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Sales\Movement
		lineageTag: 65f8ce76-0cd9-4596-b196-75b9f6bc2b89

	measure 'Net Sales Previous Year' = CALCULATE ( [Net Sales], DATEADD ( DimDate[Date], -1, YEAR ) )
		formatString: £#,0
		displayFolder: Sales\Movement
		lineageTag: c1e34e31-3089-40cc-9678-d2f359a31578

	measure 'Net Sales YoY' = DIVIDE ( [Net Sales] - [Net Sales Previous Year], [Net Sales Previous Year] )
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Sales\Movement
		lineageTag: 4871f549-c617-45ed-aa83-2b5818198fcd

	measure 'Gross Sales Previous Month' = VAR MaxSalesDate = MAX ( FactSales[SalesDate] ) VAR CurrentDate = IF ( MaxSalesDate < EOMONTH ( MaxSalesDate, 0 ), EOMONTH ( MaxSalesDate, -1 ), MaxSalesDate ) VAR PreviousDate = EOMONTH ( CurrentDate, -1 ) RETURN CALCULATE ( [Gross Sales], FILTER ( ALL ( DimDate ), DimDate[Year] = YEAR ( PreviousDate ) && DimDate[MonthNumber] = MONTH ( PreviousDate ) ) )
		formatString: £#,0
		displayFolder: Sales\Movement
		lineageTag: 5cd62187-f607-4197-a81f-23d20f0225eb

	measure 'Gross Sales MoM' = VAR MaxSalesDate = MAX ( FactSales[SalesDate] ) VAR CurrentDate = IF ( MaxSalesDate < EOMONTH ( MaxSalesDate, 0 ), EOMONTH ( MaxSalesDate, -1 ), MaxSalesDate ) VAR CurrentValue = CALCULATE ( [Gross Sales], FILTER ( ALL ( DimDate ), DimDate[Year] = YEAR ( CurrentDate ) && DimDate[MonthNumber] = MONTH ( CurrentDate ) ) ) RETURN DIVIDE ( CurrentValue - [Gross Sales Previous Month], [Gross Sales Previous Month] )
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Sales\Movement
		lineageTag: 00d07be0-b81c-4669-8d8c-da8f5e8f926e

	measure 'Orders Previous Month' = VAR MaxSalesDate = MAX ( FactSales[SalesDate] ) VAR CurrentDate = IF ( MaxSalesDate < EOMONTH ( MaxSalesDate, 0 ), EOMONTH ( MaxSalesDate, -1 ), MaxSalesDate ) VAR PreviousDate = EOMONTH ( CurrentDate, -1 ) RETURN CALCULATE ( [Orders], FILTER ( ALL ( DimDate ), DimDate[Year] = YEAR ( PreviousDate ) && DimDate[MonthNumber] = MONTH ( PreviousDate ) ) )
		formatString: #,0
		displayFolder: Sales\Movement
		lineageTag: c95ea62e-788f-47b5-ae00-b6373c487ec8

	measure 'Orders MoM' = VAR MaxSalesDate = MAX ( FactSales[SalesDate] ) VAR CurrentDate = IF ( MaxSalesDate < EOMONTH ( MaxSalesDate, 0 ), EOMONTH ( MaxSalesDate, -1 ), MaxSalesDate ) VAR CurrentValue = CALCULATE ( [Orders], FILTER ( ALL ( DimDate ), DimDate[Year] = YEAR ( CurrentDate ) && DimDate[MonthNumber] = MONTH ( CurrentDate ) ) ) RETURN DIVIDE ( CurrentValue - [Orders Previous Month], [Orders Previous Month] )
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Sales\Movement
		lineageTag: 86d8e3b7-5ac7-41ee-827e-4baca6ab010f

	measure 'Units Sold Previous Month' = VAR MaxSalesDate = MAX ( FactSales[SalesDate] ) VAR CurrentDate = IF ( MaxSalesDate < EOMONTH ( MaxSalesDate, 0 ), EOMONTH ( MaxSalesDate, -1 ), MaxSalesDate ) VAR PreviousDate = EOMONTH ( CurrentDate, -1 ) RETURN CALCULATE ( [Units Sold], FILTER ( ALL ( DimDate ), DimDate[Year] = YEAR ( PreviousDate ) && DimDate[MonthNumber] = MONTH ( PreviousDate ) ) )
		formatString: #,0
		displayFolder: Sales\Movement
		lineageTag: ba255c51-652e-4e52-89f8-acdf95f5f813

	measure 'Units Sold MoM' = VAR MaxSalesDate = MAX ( FactSales[SalesDate] ) VAR CurrentDate = IF ( MaxSalesDate < EOMONTH ( MaxSalesDate, 0 ), EOMONTH ( MaxSalesDate, -1 ), MaxSalesDate ) VAR CurrentValue = CALCULATE ( [Units Sold], FILTER ( ALL ( DimDate ), DimDate[Year] = YEAR ( CurrentDate ) && DimDate[MonthNumber] = MONTH ( CurrentDate ) ) ) RETURN DIVIDE ( CurrentValue - [Units Sold Previous Month], [Units Sold Previous Month] )
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Sales\Movement
		lineageTag: cf052e64-c08f-4cce-b94d-996b8e6604fe

	measure 'Return Rate Previous Month' = VAR MaxSalesDate = MAX ( FactSales[SalesDate] ) VAR CurrentDate = IF ( MaxSalesDate < EOMONTH ( MaxSalesDate, 0 ), EOMONTH ( MaxSalesDate, -1 ), MaxSalesDate ) VAR PreviousDate = EOMONTH ( CurrentDate, -1 ) RETURN CALCULATE ( [Return Rate], FILTER ( ALL ( DimDate ), DimDate[Year] = YEAR ( PreviousDate ) && DimDate[MonthNumber] = MONTH ( PreviousDate ) ) )
		formatString: 0.0%
		displayFolder: Sales\Movement
		lineageTag: 29737ad5-6d14-4dd6-bf90-bbeafe6ef4c0

	measure 'Return Rate Variance pp' = VAR MaxSalesDate = MAX ( FactSales[SalesDate] ) VAR CurrentDate = IF ( MaxSalesDate < EOMONTH ( MaxSalesDate, 0 ), EOMONTH ( MaxSalesDate, -1 ), MaxSalesDate ) VAR CurrentValue = CALCULATE ( [Return Rate], FILTER ( ALL ( DimDate ), DimDate[Year] = YEAR ( CurrentDate ) && DimDate[MonthNumber] = MONTH ( CurrentDate ) ) ) RETURN CurrentValue - [Return Rate Previous Month]
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Sales\Movement
		lineageTag: ea720ec6-ca9f-4627-bc0d-4f3bdc50e6a5

	measure 'Net Sales Variance vs PY' = [Net Sales] - [Net Sales Previous Year]
		formatString: £#,0;[Red]-£#,0
		displayFolder: Sales\Variance
		lineageTag: cf0eef0c-8533-4f72-a5c2-47de8e9d57ee

	measure 'Gross to Net Rate' = DIVIDE ( [Net Sales], [Gross Sales] )
		formatString: 0.0%
		displayFolder: Sales\Quality
		lineageTag: 81282731-e7a9-47b7-9d2e-c40340f6976a

	measure 'Merchandise Net Sales' = CALCULATE ( [Net Sales], FactSales[TransactionType] = "Sale", FactSales[HasValidPrice] = TRUE (), FILTER ( FactSales, VAR ProductName = TRIM ( FactSales[Description] ) VAR ProductCode = UPPER ( TRIM ( FactSales[StockCode] ) ) RETURN LEN ( ProductName ) >= 4 && LEFT ( ProductName, 1 ) <> "?" && LEFT ( ProductName, 1 ) <> "*" && NOT ( ProductCode IN { "POST", "DOT", "M", "BANK CHARGES", "AMAZONFEE", "CRUK", "C2", "D", "PADS" } ) ) )
		formatString: #,0
		displayFolder: Sales\Ranking
		lineageTag: 14241b87-5037-44ed-ae74-c969f1fc3050

	measure 'Country Sales Rank' = RANKX ( ALLSELECTED ( FactSales[Country] ), [Net Sales],, DESC, DENSE )
		formatString: #,0
		displayFolder: Sales\Ranking
		lineageTag: 89e0ce87-060a-4a95-91e4-3cdcc4073977

	measure 'Top 10 Country Net Sales' = IF ( [Country Sales Rank] <= 10, [Net Sales] )
		formatString: #,0
		displayFolder: Sales\Ranking
		lineageTag: e18e33b7-56f0-4a92-a684-a425b1574144

	measure 'Product Sales Rank' = RANKX ( ALLSELECTED ( FactSales[Description] ), [Merchandise Net Sales],, DESC, DENSE )
		formatString: #,0
		displayFolder: Sales\Ranking
		lineageTag: e22b989e-c754-478e-a819-13743fb39101

	measure 'Top 10 Product Net Sales' = IF ( NOT ISBLANK ( [Merchandise Net Sales] ) && [Product Sales Rank] <= 10, [Merchandise Net Sales] )
		formatString: #,0
		displayFolder: Sales\Ranking
		lineageTag: 59e47039-57cd-47d3-88ec-df29ae7098e3

	measure 'Top 5 Country Net Sales' = IF ( [Country Sales Rank] <= 5, [Net Sales] )
		formatString: #,0
		displayFolder: Sales\Ranking
		lineageTag: d946622c-a61c-4fbd-b82d-b0457f0b7672

	measure 'Top 5 Product Net Sales' = IF ( NOT ISBLANK ( [Merchandise Net Sales] ) && [Product Sales Rank] <= 5, [Merchandise Net Sales] )
		formatString: #,0
		displayFolder: Sales\Ranking
		lineageTag: 44e4818c-c449-4e1c-afd3-7a822029f518

	measure 'KPI Net Sales Display' = UNICHAR ( 163 ) & FORMAT ( DIVIDE ( [Net Sales], 1000000 ), "0.0" ) & "M"
		displayFolder: Sales\Display
		lineageTag: fa4a6cc9-1b1a-409b-8308-9a69cda7661a

	measure 'KPI Gross Sales Display' = UNICHAR ( 163 ) & FORMAT ( DIVIDE ( [Gross Sales], 1000000 ), "0.0" ) & "M"
		displayFolder: Sales\Display
		lineageTag: 190b83d0-68b6-436c-a87a-65172dc453c1

	measure 'KPI Orders Display' = IF ( [Orders] >= 1000, FORMAT ( DIVIDE ( [Orders], 1000 ), "0.0" ) & "K", FORMAT ( [Orders], "#,0" ) )
		displayFolder: Sales\Display
		lineageTag: d7e16b25-33f4-47dd-b0f2-cbd8e2220fb7

	measure 'KPI Units Sold Display' = IF ( [Units Sold] >= 1000000, FORMAT ( DIVIDE ( [Units Sold], 1000000 ), "0.0" ) & "M", FORMAT ( DIVIDE ( [Units Sold], 1000 ), "0.0" ) & "K" )
		displayFolder: Sales\Display
		lineageTag: 24d2499d-2478-472f-ae4b-ec8c3ca5624c

	measure 'KPI Return Rate Display' = FORMAT ( [Return Rate], "0.0%" )
		displayFolder: Sales\Display
		lineageTag: e6610564-9825-4ae9-bd45-a16535358647

	measure 'Customer Identified Net Sales' = CALCULATE ( [Net Sales], FactSales[CustomerID] <> "Unknown" )
		formatString: £#,0
		displayFolder: Customer\Core
		lineageTag: 14d5362b-bec4-4ad7-8f59-991131fc42c4

	measure 'Net Sales per Customer' = DIVIDE ( [Customer Identified Net Sales], [Customers] )
		formatString: £#,0.00
		displayFolder: Customer\Core
		lineageTag: 5f3a04f4-de13-4341-9e63-2bf08090d5fa

	measure 'Orders per Customer' = DIVIDE ( [Orders], [Customers] )
		formatString: 0.00
		displayFolder: Customer\Core
		lineageTag: 7ef235ff-81b4-47f2-b850-a828190926a0

	measure 'Customer Data Coverage' = DIVIDE ( CALCULATE ( COUNTROWS ( FactSales ), FactSales[CustomerID] <> "Unknown" ), COUNTROWS ( FactSales ) )
		formatString: 0.0%
		displayFolder: Customer\Quality
		lineageTag: 2675581f-2f00-43b8-a8ab-6802e34f49eb

	measure 'Repeat Customers' = COUNTROWS ( FILTER ( VALUES ( FactSales[CustomerID] ), FactSales[CustomerID] <> "Unknown" && CALCULATE ( [Orders] ) > 1 ) )
		formatString: #,0
		displayFolder: Customer\Core
		lineageTag: 9de20959-9320-4cb0-b889-c1fabe3ed54d

	measure 'Repeat Customer Rate' = DIVIDE ( [Repeat Customers], [Customers] )
		formatString: 0.0%
		displayFolder: Customer\Core
		lineageTag: 00611ba5-32a2-4797-9ca9-c5898946eaa0

	measure 'Active Products' = CALCULATE ( DISTINCTCOUNT ( FactSales[StockCode] ), FactSales[TransactionType] = "Sale", FactSales[HasValidPrice] = TRUE () )
		formatString: #,0
		displayFolder: Product\Core
		lineageTag: c53a32bf-656c-4729-9b1c-338d53fcf394

	measure 'Customer Sales Rank' = RANKX ( FILTER ( ALLSELECTED ( FactSales[CustomerID] ), FactSales[CustomerID] <> "Unknown" ), [Net Sales],, DESC, DENSE )
		formatString: #,0
		displayFolder: Customer\Ranking
		lineageTag: 41a912c3-b010-48a2-bbd7-621d6543ac13

	measure 'Top 10 Customer Net Sales' = IF ( [Customer Sales Rank] <= 10, [Net Sales] )
		formatString: £#,0
		displayFolder: Customer\Ranking
		lineageTag: 15d5dfa6-d870-4023-a9b1-9614deae64dc

	measure 'Product Return Rank' = RANKX ( ALLSELECTED ( FactSales[Description] ), [Return Amount],, DESC, DENSE )
		formatString: #,0
		displayFolder: Product\Ranking
		lineageTag: 32c903f5-8185-4518-af71-8e0f1898a0b9

	measure 'Top 5 Product Return Amount' = IF ( [Product Return Rank] <= 5, [Return Amount] )
		formatString: £#,0
		displayFolder: Product\Ranking
		lineageTag: 76b78166-9afb-4384-9578-d8674301e7df

	measure 'Customers Previous Month' = VAR D = MAX ( FactSales[SalesDate] ) VAR P = EOMONTH ( D, -1 ) RETURN CALCULATE ( [Customers], FILTER ( ALL ( DimDate ), DimDate[Year] = YEAR ( P ) && DimDate[MonthNumber] = MONTH ( P ) ) )
		formatString: #,0
		displayFolder: Customer\Movement
		lineageTag: 89c749dd-9928-4063-8ce8-07b59177592a

	measure 'Customers MoM' = DIVIDE ( [Customers] - [Customers Previous Month], [Customers Previous Month] )
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Customer\Movement
		lineageTag: bce7d12a-3055-4a07-b06b-119b5cfc4535

	measure 'Customer Sales Previous Month' = VAR D = MAX ( FactSales[SalesDate] ) VAR P = EOMONTH ( D, -1 ) RETURN CALCULATE ( [Customer Identified Net Sales], FILTER ( ALL ( DimDate ), DimDate[Year] = YEAR ( P ) && DimDate[MonthNumber] = MONTH ( P ) ) )
		formatString: £#,0
		displayFolder: Customer\Movement
		lineageTag: b23fdd55-381a-40e1-936f-a6089c6a1368

	measure 'Customer Sales MoM' = DIVIDE ( [Customer Identified Net Sales] - [Customer Sales Previous Month], [Customer Sales Previous Month] )
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Customer\Movement
		lineageTag: 511f1ca9-49cf-4dd8-aa90-9778bec55474

	measure 'AOV Previous Month' = VAR D = MAX ( FactSales[SalesDate] ) VAR P = EOMONTH ( D, -1 ) RETURN CALCULATE ( [Average Order Value], FILTER ( ALL ( DimDate ), DimDate[Year] = YEAR ( P ) && DimDate[MonthNumber] = MONTH ( P ) ) )
		formatString: £#,0.00
		displayFolder: Customer\Movement
		lineageTag: e9c6e2f2-594a-4de3-b6ff-fc3cc65afabe

	measure 'AOV MoM' = DIVIDE ( [Average Order Value] - [AOV Previous Month], [AOV Previous Month] )
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Customer\Movement
		lineageTag: 7e653283-d76a-456c-bc06-cd99436601eb

	measure 'Orders per Customer Previous Month' = VAR D = MAX ( FactSales[SalesDate] ) VAR P = EOMONTH ( D, -1 ) RETURN CALCULATE ( [Orders per Customer], FILTER ( ALL ( DimDate ), DimDate[Year] = YEAR ( P ) && DimDate[MonthNumber] = MONTH ( P ) ) )
		formatString: 0.00
		displayFolder: Customer\Movement
		lineageTag: 19fedafd-54bc-4906-bee1-1a8b811cd116

	measure 'Orders per Customer MoM' = DIVIDE ( [Orders per Customer] - [Orders per Customer Previous Month], [Orders per Customer Previous Month] )
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Customer\Movement
		lineageTag: c4f6b534-1ad7-4825-8363-e81e11220171

	measure 'Customer Coverage Previous Month' = VAR D = MAX ( FactSales[SalesDate] ) VAR P = EOMONTH ( D, -1 ) RETURN CALCULATE ( [Customer Data Coverage], FILTER ( ALL ( DimDate ), DimDate[Year] = YEAR ( P ) && DimDate[MonthNumber] = MONTH ( P ) ) )
		formatString: 0.0%
		displayFolder: Customer\Movement
		lineageTag: a3a1627d-7d97-4634-a934-a16f075e162b

	measure 'Customer Coverage Variance pp' = [Customer Data Coverage] - [Customer Coverage Previous Month]
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Customer\Movement
		lineageTag: 7b610d71-a138-43cf-a639-8166d0f210cc

	measure 'Active Products Previous Month' = VAR D = MAX ( FactSales[SalesDate] ) VAR P = EOMONTH ( D, -1 ) RETURN CALCULATE ( [Active Products], FILTER ( ALL ( DimDate ), DimDate[Year] = YEAR ( P ) && DimDate[MonthNumber] = MONTH ( P ) ) )
		formatString: #,0
		displayFolder: Product\Movement
		lineageTag: fc015e62-0604-466e-8e95-b1532958494a

	measure 'Active Products MoM' = DIVIDE ( [Active Products] - [Active Products Previous Month], [Active Products Previous Month] )
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Product\Movement
		lineageTag: 31825e59-ac31-4120-9d44-273d13edd4b7

	measure 'Merchandise Sales Previous Month' = VAR D = MAX ( FactSales[SalesDate] ) VAR P = EOMONTH ( D, -1 ) RETURN CALCULATE ( [Merchandise Net Sales], FILTER ( ALL ( DimDate ), DimDate[Year] = YEAR ( P ) && DimDate[MonthNumber] = MONTH ( P ) ) )
		formatString: £#,0
		displayFolder: Product\Movement
		lineageTag: ba7b808e-df33-4a8a-a17c-bf84dcc8db42

	measure 'Merchandise Sales MoM' = DIVIDE ( [Merchandise Net Sales] - [Merchandise Sales Previous Month], [Merchandise Sales Previous Month] )
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Product\Movement
		lineageTag: a2ac4ba2-35cc-47dd-8718-924097e9f124

	measure 'Return Amount Previous Month' = VAR D = MAX ( FactSales[SalesDate] ) VAR P = EOMONTH ( D, -1 ) RETURN CALCULATE ( [Return Amount], FILTER ( ALL ( DimDate ), DimDate[Year] = YEAR ( P ) && DimDate[MonthNumber] = MONTH ( P ) ) )
		formatString: £#,0
		displayFolder: Product\Movement
		lineageTag: 80dafda3-58e8-4f99-ad03-dd273b941ea3

	measure 'Return Amount MoM' = DIVIDE ( [Return Amount] - [Return Amount Previous Month], [Return Amount Previous Month] )
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Product\Movement
		lineageTag: bff58f61-b977-438c-84c2-1bb36e26cdc3

	measure 'ASP Previous Month' = VAR D = MAX ( FactSales[SalesDate] ) VAR P = EOMONTH ( D, -1 ) RETURN CALCULATE ( [Average Selling Price], FILTER ( ALL ( DimDate ), DimDate[Year] = YEAR ( P ) && DimDate[MonthNumber] = MONTH ( P ) ) )
		formatString: £#,0.00
		displayFolder: Product\Movement
		lineageTag: 67827970-b37b-4fc6-8353-cf28adaac6e7

	measure 'ASP MoM' = DIVIDE ( [Average Selling Price] - [ASP Previous Month], [ASP Previous Month] )
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Product\Movement
		lineageTag: 2b96556f-b2c0-4f0b-955d-1fcc735c4248

	measure 'KPI Customers Display' = FORMAT ( [Customers], "#,0" )
		displayFolder: Customer\Display
		lineageTag: 39ff807e-a704-42c9-a9e7-90587f36d7e8

	measure 'KPI Net Sales per Customer Display' = UNICHAR ( 163 ) & FORMAT ( [Net Sales per Customer], "#,0" )
		displayFolder: Customer\Display
		lineageTag: bd5e96c9-0e50-4196-aeab-b6dbec1d7f0a

	measure 'KPI AOV Display' = UNICHAR ( 163 ) & FORMAT ( [Average Order Value], "#,0" )
		displayFolder: Customer\Display
		lineageTag: fab9ac88-4f6e-4bbe-b47f-32150f08d5d2

	measure 'KPI Orders per Customer Display' = FORMAT ( [Orders per Customer], "0.0" ) & "x"
		displayFolder: Customer\Display
		lineageTag: bbf73bc8-fc30-42ce-8517-4f197c55db32

	measure 'KPI Customer Coverage Display' = FORMAT ( [Customer Data Coverage], "0.0%" )
		displayFolder: Customer\Display
		lineageTag: 655c78ac-eeb4-485e-8649-cb5a98babe69

	measure 'KPI Products Display' = FORMAT ( [Active Products], "#,0" )
		displayFolder: Product\Display
		lineageTag: e9c58366-220b-42f8-9677-b53ac1e4166e

	measure 'KPI Merchandise Sales Display' = UNICHAR ( 163 ) & FORMAT ( DIVIDE ( [Merchandise Net Sales], 1000000 ), "0.0" ) & "M"
		displayFolder: Product\Display
		lineageTag: 97433d41-d5de-4d41-825d-748be9678a4b

	measure 'KPI Return Amount Display' = UNICHAR ( 163 ) & FORMAT ( DIVIDE ( [Return Amount], 1000000 ), "0.0" ) & "M"
		displayFolder: Product\Display
		lineageTag: 1cb48238-d028-40c9-a07a-406e6069d1c4

	measure 'KPI ASP Display' = UNICHAR ( 163 ) & FORMAT ( [Average Selling Price], "0.00" )
		displayFolder: Product\Display
		lineageTag: 96d164b7-c434-432c-9da8-55ce2429b83e

	column CustomerStatus = IF ( FactSales[CustomerID] = "Unknown", "Unknown customer", "Identified customer" )
		dataType: string
		lineageTag: e6a8a94e-f7af-4204-838b-efc5f87c1b7e
		summarizeBy: none

	column SalesLineId
		dataType: int64
		isKey
		lineageTag: 392dc536-e7d0-4a58-a321-d3aef1f935e3
		summarizeBy: none
		sourceColumn: SalesLineId

	column InvoiceNo
		dataType: string
		lineageTag: fce2a94d-4c84-4f20-8835-7ec3eecec282
		summarizeBy: none
		sourceColumn: InvoiceNo

	column StockCode
		dataType: string
		lineageTag: 61fc516b-1e46-405c-8ef8-f5b35f3efd01
		summarizeBy: none
		sourceColumn: StockCode

	column Description
		dataType: string
		lineageTag: 9689e8c1-de64-4083-b818-8c67de64889f
		summarizeBy: none
		sourceColumn: Description

	column Quantity
		dataType: int64
		lineageTag: 922b17b5-b24c-4442-a148-20cd836f2b5f
		summarizeBy: sum
		sourceColumn: Quantity

	column InvoiceDate
		dataType: dateTime
		formatString: mmm d, yyyy h:mm AM/PM
		lineageTag: be0f97d4-2a82-4171-94a6-cc32d0b74010
		summarizeBy: none
		sourceColumn: InvoiceDate

	column SalesDate
		dataType: dateTime
		formatString: mmm d, yyyy
		lineageTag: a9e347af-6169-49c9-bee0-054d1f613acd
		summarizeBy: none
		sourceColumn: SalesDate

		annotation UnderlyingDateTimeDataType = Date

	column UnitPrice
		dataType: decimal
		formatString: £#,0.00
		lineageTag: 2afd8414-2f5f-48bb-aa1b-25f0e912f698
		summarizeBy: average
		sourceColumn: UnitPrice

	column CustomerID
		dataType: string
		lineageTag: 73bcadec-be7a-4742-8c28-ea08411c34a7
		summarizeBy: none
		sourceColumn: CustomerID

	column Country
		dataType: string
		lineageTag: 1b358003-89c9-4135-9899-4051a45cc3aa
		summarizeBy: none
		sourceColumn: Country

	column IsCancellation
		dataType: boolean
		lineageTag: b766de17-6c2e-4e28-9ffe-e0d70ac0fc41
		summarizeBy: none
		sourceColumn: IsCancellation

	column TransactionType
		dataType: string
		lineageTag: d3cc34ed-4fc9-40ac-b077-58069c7e3d75
		summarizeBy: none
		sourceColumn: TransactionType

	column NetSalesAmount
		dataType: decimal
		formatString: £#,0.00
		lineageTag: 9f3882eb-a342-44d7-8fc4-e6bb15b6c4f6
		summarizeBy: sum
		sourceColumn: NetSalesAmount

	column GrossSalesAmount
		dataType: decimal
		formatString: £#,0.00
		lineageTag: f50ae4d9-e0bf-42f9-b148-f19c922fdab4
		summarizeBy: sum
		sourceColumn: GrossSalesAmount

	column ReturnAmount
		dataType: decimal
		formatString: £#,0.00
		lineageTag: ada78f1d-4ea2-468f-b0f0-ded0a23e4c3c
		summarizeBy: sum
		sourceColumn: ReturnAmount

	column UnitsSold
		dataType: int64
		lineageTag: 9cdb74ea-0985-474a-8a4f-c2a11d3c7ee9
		summarizeBy: sum
		sourceColumn: UnitsSold

	column ReturnedUnits
		dataType: int64
		lineageTag: c77545ba-c126-4093-8b15-0293c149b183
		summarizeBy: sum
		sourceColumn: ReturnedUnits

	column HasValidPrice
		dataType: boolean
		lineageTag: 46d1644f-a275-40d2-9082-29c47246d3e2
		summarizeBy: none
		sourceColumn: HasValidPrice

	partition FactSales = m
		mode: import
		source =
				let
				    SourcePath = "C:\\Users\\ADMIN\\Documents\\Codex\\2026-07-22\\computer-use-plugin-computer-use-openai\\public-business-pbip\\data\\raw\\uci-online-retail\\Online Retail.xlsx",
				    Workbook = Excel.Workbook(File.Contents(SourcePath), null, true),
				    RawSheet = Workbook{[Item="Online Retail", Kind="Sheet"]}[Data],
				    PromotedHeaders = Table.PromoteHeaders(RawSheet, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(
				        PromotedHeaders,
				        {
				            {"InvoiceNo", type text}, {"StockCode", type text}, {"Description", type text},
				            {"Quantity", Int64.Type}, {"InvoiceDate", type datetime}, {"UnitPrice", Currency.Type},
				            {"CustomerID", type text}, {"Country", type text}
				        },
				        "en-GB"
				    ),
				    CleanText = Table.TransformColumns(
				        Typed,
				        {
				            {"InvoiceNo", each Text.Trim(_), type text},
				            {"StockCode", each Text.Trim(_), type text},
				            {"Description", each if _ = null then "Unknown product" else Text.Trim(_), type text},
				            {"CustomerID", each if _ = null or Text.Trim(_) = "" then "Unknown" else Text.Trim(_), type text},
				            {"Country", each Text.Trim(_), type text}
				        }
				    ),
				    AddLineId = Table.AddIndexColumn(CleanText, "SalesLineId", 1, 1, Int64.Type),
				    AddDate = Table.AddColumn(AddLineId, "SalesDate", each Date.From([InvoiceDate]), type date),
				    AddCancellation = Table.AddColumn(AddDate, "IsCancellation", each Text.StartsWith(Text.Upper([InvoiceNo]), "C") or [Quantity] < 0, type logical),
				    AddTransactionType = Table.AddColumn(AddCancellation, "TransactionType", each if [IsCancellation] then "Return / cancellation" else "Sale", type text),
				    AddNetSales = Table.AddColumn(AddTransactionType, "NetSalesAmount", each Number.Round([Quantity] * [UnitPrice], 2), Currency.Type),
				    AddGrossSales = Table.AddColumn(AddNetSales, "GrossSalesAmount", each if not [IsCancellation] and [Quantity] > 0 and [UnitPrice] > 0 then Number.Round([Quantity] * [UnitPrice], 2) else 0, Currency.Type),
				    AddReturnAmount = Table.AddColumn(AddGrossSales, "ReturnAmount", each if [IsCancellation] or [Quantity] < 0 then Number.Abs(Number.Round([Quantity] * [UnitPrice], 2)) else 0, Currency.Type),
				    AddUnitsSold = Table.AddColumn(AddReturnAmount, "UnitsSold", each if not [IsCancellation] and [Quantity] > 0 then [Quantity] else 0, Int64.Type),
				    AddReturnedUnits = Table.AddColumn(AddUnitsSold, "ReturnedUnits", each if [Quantity] < 0 then Number.Abs([Quantity]) else 0, Int64.Type),
				    AddValidPrice = Table.AddColumn(AddReturnedUnits, "HasValidPrice", each [UnitPrice] > 0, type logical)
				in
				    AddValidPrice

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

