table FactMarketing
	lineageTag: b074df67-e7c3-4d6d-9a28-8b347e583519

	measure Contacts = COUNTROWS ( FactMarketing )
		formatString: #,0
		displayFolder: Marketing\Core
		lineageTag: 17306521-a8c0-4a97-8d2d-d9b58f2715f2

	measure Conversions = SUM ( FactMarketing[Converted] )
		formatString: #,0
		displayFolder: Marketing\Core
		lineageTag: 7cca8780-7f85-4f83-bd75-04a14626b759

	measure 'Conversion Rate' = DIVIDE ( [Conversions], [Contacts] )
		formatString: 0.0%
		displayFolder: Marketing\Core
		lineageTag: 81b18793-1346-41d1-b016-8eb1a069867b

	measure 'Average Contact Duration' = AVERAGE ( FactMarketing[DurationSeconds] )
		formatString: #,0 "sec"
		displayFolder: Marketing\Engagement
		lineageTag: dd8358e8-a81a-4bb5-a4e8-9623084614ed

	measure 'Average Campaign Contacts' = AVERAGE ( FactMarketing[CampaignContacts] )
		formatString: 0.00
		displayFolder: Marketing\Efficiency
		lineageTag: 2e52a116-928d-46d5-a742-f44e666ea6b8

	measure 'Prior Contact Rate' = DIVIDE ( CALCULATE ( [Contacts], FactMarketing[PriorContacts] > 0 ), [Contacts] )
		formatString: 0.0%
		displayFolder: Marketing\Audience
		lineageTag: 973db1e5-ba38-42f7-99cd-7afdeedb2b37

	measure 'Cellular Contact Share' = DIVIDE ( CALCULATE ( [Contacts], FactMarketing[ContactChannel] = "cellular" ), [Contacts] )
		formatString: 0.0%
		displayFolder: Marketing\Channel
		lineageTag: 10a8922d-37e4-492b-935b-f33ca0468d70

	measure 'Successful Prior Outcome Rate' = DIVIDE ( CALCULATE ( [Contacts], FactMarketing[PriorOutcome] = "success" ), [Contacts] )
		formatString: 0.0%
		displayFolder: Marketing\Audience
		lineageTag: a357c02f-6766-40e3-a870-09e75328e118

	measure 'Conversions per 1K Contacts' = DIVIDE ( [Conversions] * 1000, [Contacts] )
		formatString: #,0.0
		displayFolder: Marketing\Efficiency
		lineageTag: 47539b1f-8a08-498d-b3ff-53b88e5914c2

	measure 'Contacts Previous Month' = VAR CurrentMonth = MAX ( FactMarketing[CampaignMonthNumber] ) RETURN CALCULATE ( [Contacts], REMOVEFILTERS ( FactMarketing[CampaignMonth], FactMarketing[CampaignMonthNumber], FactMarketing[CampaignDate] ), FactMarketing[CampaignMonthNumber] = CurrentMonth - 1 )
		formatString: #,0
		displayFolder: Marketing\Movement
		lineageTag: a03b3059-155a-4837-a328-20672bc24e33

	measure 'Contacts MoM' = DIVIDE ( [Contacts] - [Contacts Previous Month], [Contacts Previous Month] )
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Marketing\Movement
		lineageTag: 53fbd2c8-04a3-4e6a-b5aa-452362092156

	measure 'Conversions Previous Month' = VAR CurrentMonth = MAX ( FactMarketing[CampaignMonthNumber] ) RETURN CALCULATE ( [Conversions], REMOVEFILTERS ( FactMarketing[CampaignMonth], FactMarketing[CampaignMonthNumber], FactMarketing[CampaignDate] ), FactMarketing[CampaignMonthNumber] = CurrentMonth - 1 )
		formatString: #,0
		displayFolder: Marketing\Movement
		lineageTag: 58150b36-b375-4fed-ad7f-a90a4a76adf8

	measure 'Conversions MoM' = DIVIDE ( [Conversions] - [Conversions Previous Month], [Conversions Previous Month] )
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Marketing\Movement
		lineageTag: 6562bed7-7110-4003-b82d-fe231b3b7186

	measure 'Conversion Rate Previous Month' = VAR CurrentMonth = MAX ( FactMarketing[CampaignMonthNumber] ) RETURN CALCULATE ( [Conversion Rate], REMOVEFILTERS ( FactMarketing[CampaignMonth], FactMarketing[CampaignMonthNumber], FactMarketing[CampaignDate] ), FactMarketing[CampaignMonthNumber] = CurrentMonth - 1 )
		formatString: 0.0%
		displayFolder: Marketing\Movement
		lineageTag: 858df9e4-86e2-4f0e-a2fa-43f65c643720

	measure 'Conversion Rate Variance pp' = [Conversion Rate] - [Conversion Rate Previous Month]
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Marketing\Movement
		lineageTag: 2606a67c-8604-444a-877a-1f2f978a34e8

	measure 'Average Duration Previous Month' = VAR CurrentMonth = MAX ( FactMarketing[CampaignMonthNumber] ) RETURN CALCULATE ( [Average Contact Duration], REMOVEFILTERS ( FactMarketing[CampaignMonth], FactMarketing[CampaignMonthNumber], FactMarketing[CampaignDate] ), FactMarketing[CampaignMonthNumber] = CurrentMonth - 1 )
		formatString: #,0 "sec"
		displayFolder: Marketing\Movement
		lineageTag: 9a59fcf3-9d9e-4be0-8c8e-1835fed0241f

	measure 'Average Duration MoM' = DIVIDE ( [Average Contact Duration] - [Average Duration Previous Month], [Average Duration Previous Month] )
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Marketing\Movement
		lineageTag: 507e994d-37e0-4aa1-8e89-cf5b9415db84

	measure 'Average Campaign Contacts Previous Month' = VAR CurrentMonth = MAX ( FactMarketing[CampaignMonthNumber] ) RETURN CALCULATE ( [Average Campaign Contacts], REMOVEFILTERS ( FactMarketing[CampaignMonth], FactMarketing[CampaignMonthNumber], FactMarketing[CampaignDate] ), FactMarketing[CampaignMonthNumber] = CurrentMonth - 1 )
		formatString: 0.00
		displayFolder: Marketing\Movement
		lineageTag: 2928289e-0986-4f50-b4c5-89b523fe2c84

	measure 'Average Campaign Contacts MoM' = DIVIDE ( [Average Campaign Contacts] - [Average Campaign Contacts Previous Month], [Average Campaign Contacts Previous Month] )
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Marketing\Movement
		lineageTag: 5a13da3a-11b4-4a9d-adb1-c2538c2c58a4

	measure 'KPI Contacts Display' = IF ( [Contacts] >= 1000, FORMAT ( DIVIDE ( [Contacts], 1000 ), "0.0" ) & "K", FORMAT ( [Contacts], "#,0" ) )
		displayFolder: Marketing\Display
		lineageTag: 994068e4-a022-49bf-b23f-f0974f38996a

	measure 'KPI Conversions Display' = IF ( [Conversions] >= 1000, FORMAT ( DIVIDE ( [Conversions], 1000 ), "0.0" ) & "K", FORMAT ( [Conversions], "#,0" ) )
		displayFolder: Marketing\Display
		lineageTag: e5416531-ac82-4a1d-832b-10954294b0aa

	measure 'KPI Conversion Rate Display' = FORMAT ( [Conversion Rate], "0.0%" )
		displayFolder: Marketing\Display
		lineageTag: c8931842-a88d-4f1a-bdc5-c2e861b2b8a1

	measure 'KPI Average Duration Display' = FORMAT ( [Average Contact Duration], "#,0" ) & " sec"
		displayFolder: Marketing\Display
		lineageTag: 4227642b-80c2-4477-8df7-a4f90151e847

	measure 'KPI Average Contacts Display' = FORMAT ( [Average Campaign Contacts], "0.0" ) & "x"
		displayFolder: Marketing\Display
		lineageTag: 54f14430-0226-4b7d-929a-4ddb16942786

	measure 'Prior Contact Rate Previous Month' = VAR M = MAX ( FactMarketing[CampaignMonthNumber] ) RETURN CALCULATE ( [Prior Contact Rate], REMOVEFILTERS ( FactMarketing[CampaignMonth], FactMarketing[CampaignMonthNumber], FactMarketing[CampaignDate] ), FactMarketing[CampaignMonthNumber] = M - 1 )
		formatString: 0.0%
		displayFolder: Marketing\Movement
		lineageTag: c03bb695-5c48-42cf-9290-d531d3babdd9

	measure 'Prior Contact Rate Variance pp' = [Prior Contact Rate] - [Prior Contact Rate Previous Month]
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Marketing\Movement
		lineageTag: 7052f9a2-e758-4bfa-8334-39b309ee7d79

	measure 'Cellular Share Previous Month' = VAR M = MAX ( FactMarketing[CampaignMonthNumber] ) RETURN CALCULATE ( [Cellular Contact Share], REMOVEFILTERS ( FactMarketing[CampaignMonth], FactMarketing[CampaignMonthNumber], FactMarketing[CampaignDate] ), FactMarketing[CampaignMonthNumber] = M - 1 )
		formatString: 0.0%
		displayFolder: Marketing\Movement
		lineageTag: 76ef34ef-20e9-468f-a536-69362d366349

	measure 'Cellular Share Variance pp' = [Cellular Contact Share] - [Cellular Share Previous Month]
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Marketing\Movement
		lineageTag: 3eae48e5-ee7c-425e-a100-5bda16a4bee6

	measure 'Successful Prior Rate Previous Month' = VAR M = MAX ( FactMarketing[CampaignMonthNumber] ) RETURN CALCULATE ( [Successful Prior Outcome Rate], REMOVEFILTERS ( FactMarketing[CampaignMonth], FactMarketing[CampaignMonthNumber], FactMarketing[CampaignDate] ), FactMarketing[CampaignMonthNumber] = M - 1 )
		formatString: 0.0%
		displayFolder: Marketing\Movement
		lineageTag: 47a4abd1-a3d7-4b57-9c31-b97746da7c49

	measure 'Successful Prior Rate Variance pp' = [Successful Prior Outcome Rate] - [Successful Prior Rate Previous Month]
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: Marketing\Movement
		lineageTag: a4151500-f5ae-48f8-a799-706a772a1c0d

	measure 'KPI Prior Contact Rate Display' = FORMAT ( [Prior Contact Rate], "0.0%" )
		displayFolder: Marketing\Display
		lineageTag: 74d7f7da-3b08-4435-8ef7-d3988a0e833b

	measure 'KPI Conversions per 1K Display' = FORMAT ( [Conversions per 1K Contacts], "#,0" )
		displayFolder: Marketing\Display
		lineageTag: b52f4903-572b-4bc7-91fb-d987ca957e0e

	measure 'KPI Cellular Share Display' = FORMAT ( [Cellular Contact Share], "0.0%" )
		displayFolder: Marketing\Display
		lineageTag: 299627a7-79aa-4a44-ad95-9cbe9d2e3688

	measure 'KPI Successful Prior Display' = FORMAT ( [Successful Prior Outcome Rate], "0.0%" )
		displayFolder: Marketing\Display
		lineageTag: ee7c38ef-e142-434b-88d8-f92f1f8b9363

	column ContactId
		dataType: int64
		isKey
		lineageTag: 038f2025-6ffb-462d-b980-52e623cf195d
		summarizeBy: none
		sourceColumn: ContactId

	column Age
		dataType: int64
		formatString: 0
		lineageTag: 5a00ad0a-7b07-43b8-be47-563579dfbf78
		summarizeBy: none
		sourceColumn: Age

	column Job
		dataType: string
		lineageTag: 329191da-ed04-405c-8cfb-335587d183cb
		summarizeBy: none
		sourceColumn: Job

	column MaritalStatus
		dataType: string
		lineageTag: 36ad22ff-ca93-486f-881f-5da8d7f781a6
		summarizeBy: none
		sourceColumn: MaritalStatus

	column Education
		dataType: string
		lineageTag: c33b9417-cd9d-400f-8537-51004862f71f
		summarizeBy: none
		sourceColumn: Education

	column CreditDefault
		dataType: string
		lineageTag: 47067214-f051-407e-859e-f3ab96080573
		summarizeBy: none
		sourceColumn: CreditDefault

	column HousingLoan
		dataType: string
		lineageTag: be1abef8-54eb-4d42-9865-7267bc2662fd
		summarizeBy: none
		sourceColumn: HousingLoan

	column PersonalLoan
		dataType: string
		lineageTag: 9d3f53f1-33b9-406a-836e-87ed45bd562b
		summarizeBy: none
		sourceColumn: PersonalLoan

	column ContactChannel
		dataType: string
		lineageTag: 8efcb051-dbce-4550-a491-9b8603f09656
		summarizeBy: none
		sourceColumn: ContactChannel

	column CampaignMonth
		dataType: string
		lineageTag: 884606f5-cf66-402f-9229-ec5e81fdaf37
		summarizeBy: none
		sourceColumn: CampaignMonth
		sortByColumn: CampaignMonthNumber

	column CampaignMonthNumber
		dataType: int64
		formatString: 0
		lineageTag: a80ad621-bd90-412e-91b0-819b5863c722
		summarizeBy: none
		sourceColumn: CampaignMonthNumber

	column ContactDayOfWeek
		dataType: string
		lineageTag: 6e2830de-fa91-406a-a92b-bc746fff4ce3
		summarizeBy: none
		sourceColumn: ContactDayOfWeek

	column DurationSeconds
		dataType: int64
		formatString: 0
		lineageTag: 58faee02-d4c9-45e8-99b9-f938c0e0906c
		summarizeBy: none
		sourceColumn: DurationSeconds

	column CampaignContacts
		dataType: int64
		formatString: 0
		lineageTag: eb7537fc-306d-44ea-88a1-46dabc468671
		summarizeBy: none
		sourceColumn: CampaignContacts

	column DaysSincePriorContact
		dataType: int64
		formatString: 0
		lineageTag: 940d1040-4cac-42aa-a08a-b46dbd88c626
		summarizeBy: none
		sourceColumn: DaysSincePriorContact

	column PriorContacts
		dataType: int64
		formatString: 0
		lineageTag: 600936ce-b7c6-4e46-9db1-73a9e3bbea3d
		summarizeBy: none
		sourceColumn: PriorContacts

	column PriorOutcome
		dataType: string
		lineageTag: 25729da2-3943-4877-8878-e6ca501c1e9b
		summarizeBy: none
		sourceColumn: PriorOutcome

	column EmploymentVariationRate
		dataType: double
		formatString: 0.0
		lineageTag: 460a6497-d426-4098-9a50-a26c95a04ab9
		summarizeBy: none
		sourceColumn: EmploymentVariationRate

	column ConsumerPriceIndex
		dataType: double
		formatString: 0.000
		lineageTag: 3c552200-2424-4c41-b3d1-7a5a19ff620e
		summarizeBy: none
		sourceColumn: ConsumerPriceIndex

	column ConsumerConfidenceIndex
		dataType: double
		formatString: 0.0
		lineageTag: 574f91c3-c6c1-4b2a-9aef-1379b06b2abb
		summarizeBy: none
		sourceColumn: ConsumerConfidenceIndex

	column Euribor3Month
		dataType: double
		formatString: 0.000
		lineageTag: ce203b82-b282-46f3-b93f-287511d66ca3
		summarizeBy: none
		sourceColumn: Euribor3Month

	column NumberEmployed
		dataType: double
		formatString: #,0.0
		lineageTag: 64080f68-3e4f-4028-a9b8-30840d11a727
		summarizeBy: none
		sourceColumn: NumberEmployed

	column SubscriptionOutcome
		dataType: string
		lineageTag: d8fb31e2-68b4-4fc3-ab95-651e56f54926
		summarizeBy: none
		sourceColumn: SubscriptionOutcome

	column Converted
		dataType: int64
		formatString: 0
		lineageTag: ba64dca3-9972-4d1e-8e9e-8f362ae7abe4
		summarizeBy: sum
		sourceColumn: Converted

	column AgeBand
		dataType: string
		lineageTag: 6684e76e-c93d-4750-840e-56d9aa7057f1
		summarizeBy: none
		sourceColumn: AgeBand

	column DurationBand
		dataType: string
		lineageTag: f103d621-9a31-4997-9c52-fc4ee18c3cf7
		summarizeBy: none
		sourceColumn: DurationBand

	column ContactFrequencyBand
		dataType: string
		lineageTag: ae34fbb2-2c45-4f70-b38d-2bf3aebaa520
		summarizeBy: none
		sourceColumn: ContactFrequencyBand

	column PriorContacted
		dataType: string
		lineageTag: 4db5eea6-83c1-4247-a51c-00fd8d5004d7
		summarizeBy: none
		sourceColumn: PriorContacted

	column month
		dataType: string
		lineageTag: bd1b73b3-6cea-4a0d-b257-f3196f849301
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column CampaignDate
		dataType: dateTime
		formatString: M/d/yyyy
		lineageTag: 4d9c7c2a-bc9e-4a1f-9a62-7f690c497a24
		summarizeBy: none
		sourceColumn: CampaignDate

		annotation UnderlyingDateTimeDataType = Date

	partition FactMarketing = m
		mode: import
		source =
				let
				    SourcePath = "C:\\Users\\ADMIN\\Documents\\Codex\\2026-07-22\\computer-use-plugin-computer-use-openai\\public-business-pbip\\data\\raw\\uci-bank-marketing\\bank-additional\\bank-additional\\bank-additional-full.csv",
				    RawCsv = Csv.Document(File.Contents(SourcePath), [Delimiter=";", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    PromotedHeaders = Table.PromoteHeaders(RawCsv, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(
				        PromotedHeaders,
				        {
				            {"age", Int64.Type}, {"job", type text}, {"marital", type text}, {"education", type text},
				            {"default", type text}, {"housing", type text}, {"loan", type text}, {"contact", type text},
				            {"month", type text}, {"day_of_week", type text}, {"duration", Int64.Type}, {"campaign", Int64.Type},
				            {"pdays", Int64.Type}, {"previous", Int64.Type}, {"poutcome", type text},
				            {"emp.var.rate", type number}, {"cons.price.idx", type number}, {"cons.conf.idx", type number},
				            {"euribor3m", type number}, {"nr.employed", type number}, {"y", type text}
				        },
				        "en-US"
				    ),
				    AddContactId = Table.AddIndexColumn(Typed, "ContactId", 1, 1, Int64.Type),
				    AddConverted = Table.AddColumn(AddContactId, "Converted", each if [y] = "yes" then 1 else 0, Int64.Type),
				    AddMonthNumber = Table.AddColumn(
				        AddConverted,
				        "CampaignMonthNumber",
				        each List.PositionOf({"jan","feb","mar","apr","may","jun","jul","aug","sep","oct","nov","dec"}, [month]) + 1,
				        Int64.Type
				    ),
				    AddMonthName = Table.AddColumn(AddMonthNumber, "CampaignMonth", each Date.MonthName(#date(2000, [CampaignMonthNumber], 1), "en-US"), type text),
				    AddCampaignDate = Table.AddColumn(AddMonthName, "CampaignDate", each #date(2000, [CampaignMonthNumber], 1), type date),
				    AddAgeBand = Table.AddColumn(
				        AddCampaignDate,
				        "AgeBand",
				        each if [age] < 30 then "Under 30" else if [age] < 40 then "30–39" else if [age] < 50 then "40–49" else if [age] < 60 then "50–59" else "60+",
				        type text
				    ),
				    AddDurationBand = Table.AddColumn(
				        AddAgeBand,
				        "DurationBand",
				        each if [duration] < 60 then "Under 1 min" else if [duration] < 180 then "1–3 min" else if [duration] < 300 then "3–5 min" else if [duration] < 600 then "5–10 min" else "10+ min",
				        type text
				    ),
				    AddContactBand = Table.AddColumn(
				        AddDurationBand,
				        "ContactFrequencyBand",
				        each if [campaign] = 1 then "1 contact" else if [campaign] <= 3 then "2–3 contacts" else if [campaign] <= 5 then "4–5 contacts" else "6+ contacts",
				        type text
				    ),
				    AddPriorContact = Table.AddColumn(AddContactBand, "PriorContacted", each if [previous] > 0 then "Previously contacted" else "First-time contact", type text),
				    Renamed = Table.RenameColumns(
				        AddPriorContact,
				        {
				            {"age", "Age"}, {"job", "Job"}, {"marital", "MaritalStatus"}, {"education", "Education"},
				            {"default", "CreditDefault"}, {"housing", "HousingLoan"}, {"loan", "PersonalLoan"},
				            {"contact", "ContactChannel"}, {"day_of_week", "ContactDayOfWeek"}, {"duration", "DurationSeconds"},
				            {"campaign", "CampaignContacts"}, {"pdays", "DaysSincePriorContact"}, {"previous", "PriorContacts"},
				            {"poutcome", "PriorOutcome"}, {"emp.var.rate", "EmploymentVariationRate"},
				            {"cons.price.idx", "ConsumerPriceIndex"}, {"cons.conf.idx", "ConsumerConfidenceIndex"},
				            {"euribor3m", "Euribor3Month"}, {"nr.employed", "NumberEmployed"}, {"y", "SubscriptionOutcome"}
				        }
				    )
				in
				    Renamed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

