table RiskDriverImportance
	lineageTag: 39316fd4-81d5-4a2f-afdf-4e8c005ae9e4

	column Driver
		dataType: string
		lineageTag: af1394fa-fc6a-44fb-a40a-df547e91bde0
		summarizeBy: none
		sourceColumn: Driver

	column Importance
		dataType: double
		formatString: 0.0%
		lineageTag: 8374d2cf-ad38-4acb-840d-6c8117cb0e73
		summarizeBy: sum
		sourceColumn: Importance

	column Rank
		dataType: int64
		formatString: 0
		lineageTag: 399cdf48-5013-4124-9a2e-0af9db655150
		summarizeBy: min
		sourceColumn: Rank

	column ModelAUC
		dataType: double
		formatString: 0.000
		lineageTag: d266bd91-d35b-4f82-8a98-ce0748335fa8
		summarizeBy: max
		sourceColumn: ModelAUC

	column DriverLabel =
			SWITCH (
				RiskDriverImportance[Driver],
				"Debt-to-Income Ratio", "DTI Ratio",
				"Home Ownership", "Ownership",
				"Income Verification", "Verification",
				RiskDriverImportance[Driver]
			)
		dataType: string
		lineageTag: 2c05ee84-8ff2-4475-986f-d47093c8e44f
		summarizeBy: none

	partition RiskDriverImportance = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\PowerBI Dashboard - KhoiPort\04_FinTech_Credit_Risk\Data\risk_driver_importance.csv"), [Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Types = Table.TransformColumnTypes(Headers, {{"Driver", type text}, {"Importance", type number}, {"Rank", Int64.Type}, {"ModelAUC", type number}}, "en-US")
				in
				    Types

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

